name: CI Tests
# this will technically run again on merge to master, should limit it
on:
  pull_request:
    branches: [ main ]

jobs: 
    basic-test:
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v4
    
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 18.19.1
        
        # - name: Get node version
        #   id: node
        #   run: |
        #     echo "::set-output name=version::$(node -v)"

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Check docker.hub limit
          env:
            USER: ${{ secrets.DOCKER_USERNAME }}
            PASS: ${{ secrets.DOCKER_PASSWORD }}
          run: npm run docker:limit
          
        - name: npm Install
          run: npm install

        - name: Test Docker Pull
          run: npm test